---
:mdb:
  :test_fixture: true
  :breakpoints: []
  :timeout: null
  :hwtool: sim
  :tools:
    :sim:
      :uart1io.uartioenabled: true
      :uart1io.output: window
  :serialport:
    :baudrate: 115200
    :data_bits: 8
    :stop_bits: 1
    :parity: :none
...
